packages:
  - "packages/*"
  - "examples/*"
  - "apps/*"

catalog:
  vitest: ^4.0.18
  "@types/node": ^25.2.0
  zod: ^4.3.6
  tsdown: 0.19.0-beta.3
  picocolors: ^1.1.1
  typescript: ^5.9.3
  concurrently: ^9.2.1
  commander: ^14.0.3
  dedent: ^1.7.1
