packages:
  - "packages/*"
  - "examples/*"
  - "apps/*"
  - "bundle-analyzer"

catalog:
  vitest: ^4.0.7
  "@types/node": ^25.0.3
  zod: ^4.3.5
  tsdown: 0.19.0-beta.3
  picocolors: ^1.1.1
  typescript: ^5.9.3
  concurrently: ^9.2.1
  commander: ^14.0.2
  dedent: ^1.7.1
